### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by ritikagarwal231** [Aloinn/Spacestagram-page#1]
Just came across this project and really loved it.
I am currently working on the exact same tech stack that you have used for this project and just looking at different projects to get some sort of inspiration to make some cool projects like this and also to get better with this tech Stack.
It will mean a lot to me if you can help me with that in any way possible.
Also i am more than happy if you need help or want to work together on some project.

**Comment by Aloinn** [comment]
Feel free to take a look at the source code repository:
https://github.com/Aloinn/Spacestagram

This repository is only for hosting using GitHub pages.
Feel free to fork the source code.

To install the dependencies and run a local environment:
```bash
yarn
quasar dev
```

Here are the documentations for Vue3:
https://v3.vuejs.org/guide/introduction.html

Here are the documentations for Quasar:
https://quasar.dev/

Let me know if you have any trouble setting up the environment
